#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  hendrix-frontend
        bind *:80
        mode http
        default_backend hendrix-backend
backend hendrix-backend
        balance roundrobin
        server 141836-web-01 34.224.16.103:80 check
        server 141836-web-02 34.239.250.26:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# test for syntax errors
sudo haproxy -c

# restart haproxy after updating the settings
sudo service haproxy restart
