#!/usr/bin/env bash
# This script displays the text 'To infinity and beyond' indefinetely
# Add a sleep 2 in-between each iteration of the loop

while true
do
	echo "To infinity and beyond"
	sleep 2
done
