#!/usr/bin/env bash
# script that displays Best School 10 times.
# Requirements: You must use the until loop (for and while are forbidden)

count=0

until [ $count -eq 10 ]
do
	echo "Best School"
	((count++))
done
